### ISSUE TITLE
海南地点的识别结果没有’市‘

### ISSUE THREAD

**Issue by thesillydog** [lijiarui/ticket-bot#112]
**海南识别为海南，格式不同
北京上海等都识别为北京市、上海市。**
![image](https://user-images.githubusercontent.com/9498159/33806028-ab0fb1b6-ddfc-11e7-884f-e811031c79ae.png)
是否需要统一格式

**Comment by lijiarui** [comment]
和 #114 一样 另外，没有海南市吧，只有海南省。
应该是 海口市？
