### ISSUE TITLE
arriaveTimePeriad无法选中

### ISSUE THREAD

**Issue by mushr6om7** [lijiarui/ticket-bot#12]
那个是浦东的，这个吧:东方航空MU5128空中客车 A330-300(大型)20:55首都国际机场T2 23:15虹桥国际机场T2

23:15无法被选中。

**Comment by lijiarui** [comment]
多尝试几次，把无关的entity 删除后再加入。
![image](https://user-images.githubusercontent.com/6419514/31806434-6add00aa-b52d-11e7-8ed1-c5d1654f5bc8.png)
