### ISSUE TITLE
how to label time period

### ISSUE THREAD

**Issue by lijiarui** [lijiarui/ticket-bot#2]
User say: `预订一个下周一上午8点到12点之间从北京到上海的头等舱机票，要南方航空的，价格8折以内`

How to get `8点到12点` as a time period.

Now I can get `8点` and `12点`

* depart_time_period: `8点到12点之间`
* depart_time_period_begin: `8点`
* depart_time_period_end: `10点`

**Comment by mushr6om7** [comment]
已录入语料
