### ISSUE TITLE
时间段——"时间不要太晚"

### ISSUE THREAD

**Issue by mushr6om7** [lijiarui/ticket-bot#30]
帮我订个明天重庆到北京的机票吧，时间不要太晚的都可以。谢谢。刚接到周六要到公司的通知。
--

**Comment by lijiarui** [comment]
可以加一个类似`timeOption` 的选项， value 可以是 `不要太晚` 这样的值，你设置几个不同的点:
* morning: 05:00-10:00
* noon:10:00-13:00
* afternoon:13:00-17:00
* evening:17:00-21:00
* night:21:00-00:00
如果不要太晚就可以选择 not night，也就是 morning,noon,afternoon,evening 的值。具体你看一下 Prebuild Agent 里面的Small talk 是如何定义的。

**Comment by mushr6om7** [comment]
放在了timeChoose的entity里
