### ISSUE TITLE
Special User say sentences

### ISSUE THREAD

**Issue by lijiarui** [lijiarui/ticket-bot#4]
The follow should add to api.ai
* 帮我订一个7点左右的机票
* 帮我订一个七点左右的机票
* 今晚8:20的，帮我定一下，谢谢！
* 帮我定一个北京到上海的机票
* 帮我定一张明天北京到上海的机票（明天: departDate）
* 帮我订一张明天到广州的机票(明天: arriveDate)

**Comment by lijiarui** [comment]
@mushr6om7

**Comment by mushr6om7** [comment]
已加入语料集
