### ISSUE TITLE
Intent book-flight entities name & type

### ISSUE THREAD

**Issue by mushr6om7** [lijiarui/ticket-bot#43]
|entity        | isList          | 示例  |
| ------------- |:-------------:| -----:|
| airline      | Y | 帮我订一张票，最好是**东航**或**国航**的。 |
| aPort     | Y|   我明天回京，帮我订张票，到**首都国际机场**或**南苑机场**都行|
| arriveCity |Y    | 帮我订一张去**潍坊**的机票，没有的话到**青岛**的也行。 |
|arriveDate|Y|帮我订一张机票，**明后天**到上海的都行。|
|arriveTimePeriod|Y|帮我订一张明天**晚上**到北京机票，最好**10点前**到。|
|cabinInfo|Y|**商务舱**或者**头等舱**|
|departCity|Y|明天上午从**北京**出发，如果没有票了，从**天津**出发也行，我先坐高铁去天津。|
|departDate|Y|我明天在上海开会，帮我订**今天**或者**明天**的票。|
|departTimePeriod|Y|给我订张明天**上午**去上海的机票，最好**九点到十点之间**的。|
|dPort|Y|我明天去上海，帮我订张票，从**首都国际机场**出发或者**南苑**出发的都行。|
|flight|Y|给我定张明天的机票，**CA1398**或**CA1819**。|
|price|N| |
|quantity|N||
|departTime|Y|**1:45**的或者**两点**的|
|arriveTime|Y|**1:45**的或者**两点**的|
|city|Y|**北京**或**天津**|
|port|Y|**首都国际机场**或者**南苑**都行|
|timeChoose|Y|帮我订张机票，**不要太晚**的，**优先12点**的|
|replyTimePeriod|Y|**下午**或者**晚上**的|
|changeEntity|Y|**提前**或**推迟** **一个班次**吧|
|replyDate|Y|**明天**或**后天**|
|replyTime|Y|**12点**或**1点**|

**Comment by lijiarui** [comment]
### aPlace && dPlace
* flight

### aPlace
* aPort
* arriveCity

### dPlace
* departCity
* dPort

### Date
* arriveDate
* arriveTime
* arriveTimePeriod
* departDate
* departTime
* departTimePeriod


### Place
* city
* port

### Time
* replyDate
* replyTime

### Other
* airline
* cabinInfo
* price
* quantity

### Not sure
* changEntity

**Comment by lijiarui** [comment]
@mushr6om7 `changEntity` should think more and give some reason.

**Comment by mushr6om7** [comment]
changEntity里包含了所有跟修改信息有关的东西，比如“提前”“延后”“班次”“一个小时”，代码处理的时候，如果changeEntity不为空，则判断List里是否包含“班次”“小时”这些需要被修改的实体，然后判断是延后还是提前
