### ISSUE TITLE
sys.time异常汇总

### ISSUE THREAD

**Issue by mushr6om7** [lijiarui/ticket-bot#48]
1. 
![image](https://user-images.githubusercontent.com/32808045/32061148-7b481904-baa3-11e7-87cd-9f87586949df.png)

实际提取结果："time-period": "",
期望的提取结果："time-period": "两点多",

2.
![image](https://user-images.githubusercontent.com/32808045/32722837-353f3a94-c8a6-11e7-80f3-360ce4c21cf2.png)

 
实际提取结果："time-period": "18:00:00/07:00:00",
期望的提取结果："time-period": "18:00:00/19:00:00",

**Comment by lijiarui** [comment]
1.  参考 #36  所有的输入需要做预处理。
2. 你多试一下，没理由出问题的。
