### ISSUE TITLE
无法标注的user_say

### ISSUE THREAD

**Issue by mushr6om7** [lijiarui/ticket-bot#54]
- 给他定吧

- 	那定我的吧
- 身份信息:	*****，某某某
- 订完票麻烦告诉我声大致时间，我需要提前回家拿点东西
- 行么？行的话我就明天收拾下过去。
- 	对，我比他们晚去一天
- 培训时间8月4日上午9点，地点济宁市市中区，通信大厦，多功能厅，联系人
- 	帮我找一下
- 	买完了哦一声哈三克油
- 他还没确定 有个问题在解决
- 	周五就得干活，周五的机票到了，就中午了。
- 	某某某好像自己找你定
- 	我俩不一起走
- 	你看着订就行
- 在不？ 我想订机票是找你不？
- 	我发给他们
- 	噢，那跟他一起吧
- 	我看一下
- 提前一个或者延后一个班次吧，可行
- 	提前吧，刚才看还590
- 	我和某某某要10点半和客户开会
- 	可以吧？兄弟
- 我这里没高铁，帮我直接定机票吧，谢谢。

- 帮某某某定同一班,谢谢
- 确定是榆林起飞吧？

**Comment by lijiarui** [comment]
`在不？ 我想订机票是找你不？` 有intent  没有entity

**Comment by mushr6om7** [comment]
```
 在不？ 我想订机票是找你不？ 
 我这里没高铁，帮我直接定机票吧，谢谢。
```

加入bookFlight

```
提前一个或者延后一个班次吧，可行
提前吧，刚才看还590
```

加入changeAirplane

**仍未归类的**

- 给他定吧

- 	那定我的吧
- 身份信息:	*****，某某某
- 订完票麻烦告诉我声大致时间，我需要提前回家拿点东西
- 行么？行的话我就明天收拾下过去。
- 	对，我比他们晚去一天
- 培训时间8月4日上午9点，地点济宁市市中区，通信大厦，多功能厅，联系人
- 	帮我找一下
- 	买完了哦一声哈三克油
- 他还没确定 有个问题在解决
- 	周五就得干活，周五的机票到了，就中午了。
- 	某某某好像自己找你定
- 	我俩不一起走
- 	你看着订就行
- 	我发给他们
- 	噢，那跟他一起吧
- 	我看一下
- 	我和某某某要10点半和客户开会
- 	可以吧？兄弟
- 帮某某某定同一班,谢谢
- 确定是榆林起飞吧？

**Comment by mushr6om7** [comment]
`身份信息:	*****，某某某` 归入intent`PassengerInfo`
其他的话归入intent `Meaningless`
