### ISSUE TITLE
扩充现有的intent 语料

### ISSUE THREAD

**Issue by lijiarui** [lijiarui/ticket-bot#55]
@mushr6om7
- [ ] 现有的 reply-all-time 和 reply-all-place 的语料是空的，编辑一些进去。
- [ ] 另外，reply-place 类似`北京，最好下午出发`的语料应该放到 reply-all-place 里面。其他相关的也修改下。
- [ ] 把所有intent 的格式从 `reply-place` 形式换成`replyPlace`

**Comment by mushr6om7** [comment]
已修改
