### ISSUE TITLE
在每一个intent 下面把所有相关的entity都列出来

### ISSUE THREAD

**Issue by lijiarui** [lijiarui/ticket-bot#57]
@mushr6om7

change intent 相关的entity 都有哪些，在下面的parameter中都列出来。 其他的intent 同理。
除了增加entity外，也从你的理解中编一些语料加进去。

![image](https://user-images.githubusercontent.com/6419514/32374158-7c8a84f2-c0d7-11e7-9491-68df8d69dcf8.png)

**Comment by mushr6om7** [comment]
已加
