### ISSUE TITLE
后期做订火车票时最好将站点的entity名同样设置为“port”

### ISSUE THREAD

**Issue by mushr6om7** [lijiarui/ticket-bot#66]
考虑到虹桥站既是火车站又是飞机场
“到虹桥站吧”这句话既可以用在定火车票又可以用在定机票，所以归到replyExactPlace的意图里，并将虹桥标为aPort。
后面做订火车票功能时将站点entity名同样设置为“port”可以方便类似这种情况的实体提取。

**Comment by lijiarui** [comment]
没问题。 port 在航班里面表示机场， 在火车里面表示火车站。
