### ISSUE TITLE
[Intent List] Ignore the less important intent.

### ISSUE THREAD

**Issue by lijiarui** [lijiarui/ticket-bot#67]
The bot no need to be that smart at the moment. 
### Do not want to deal with the following intent at the moment.
* bookMoreAirplane
* roundTrip
* search
### Deal with the following intent:
- [x] book
- [x] flightBook
- [x] replyExactPlace
- [x] replyExactTime
- [x] replyFlightPlace
- [ ] replyFilghtTime
- [x] replyPlace
- [ ] replyQuantity
- [x] replyTime
---

- [ ] changeAirplane
- [ ] chooseTime
- [ ] ending
- [ ] no
- [ ] yes

@mushr6om7 please add an intro of all of the intent.

**Comment by mushr6om7** [comment]
Do not want to deal with the following intent at the moment.

bookMoreAirplane //一句话里有多个订票需求
roundTrip //带有订返程票需求的意图
search //查询已定机票


Deal with the following intent:

book //没有明确topic（订机票、火车票或酒店）的预定意图
flightBook //订机票意图
replyExactPlace //含有确切出发地（站点）或到达地（站点）的意图（无法识别属于哪个topic）
replyExactTime//含有确切出发时间或到达时间的意图（无法识别属于哪个topic）
replyFlightPlace //只含有与机票有关的机场信息，无法判断是出发或到达的意图
replyFilghtTime //只含有与机票有关的时间信息，无法判断是出发或到达的意图
replyPlace //只含有地点信息的意图，无法判断是出发或到达，也无法判断属于哪个topic
replyQuantity //只含有订票张数的意图，无法判断属于哪个topic
replyTime //只含有时间信息的意图，无法判断是出发或到达，也无法判断属于哪个topic
 changeAirplane //在订机票时修改已声明过的实体意图
 chooseTime //通过时间选择具体班次，无法判断属于哪个topic
 ending //用户的结束语
 no //含有否定的意图
 yes //含有肯定的意图

**Comment by lijiarui** [comment]
![image](https://user-images.githubusercontent.com/6419514/33159283-857cc6e0-d04c-11e7-90cf-b5623c687b8f.png)

这个同时还有time 的信息，似乎不应该放在replyPlace 里面。应该放在哪里面，我也么想好。

@mushr6om7  有什么想法么

**Comment by mushr6om7** [comment]
这句话里的北京可能是出发也可能是到达，到达的情况：

-我要买张机票
-好的，您要去哪里呢
-北京，最好下午出发

没法判断是出发还是到达，所以放在了replyPlace里

**Comment by lijiarui** [comment]
see #75
