### ISSUE TITLE
列出book 和 flightBook 下面的entity

### ISSUE THREAD

**Issue by lijiarui** [lijiarui/ticket-bot#70]
用来封装接口

**Comment by lijiarui** [comment]
@mushr6om7 所有相关的都这样列一下。

**Comment by mushr6om7** [comment]
列到issue里？只列entity的名字？

**Comment by lijiarui** [comment]
每个intent 下面对应的entity。如果api.ai 下面都放了，我去api.ai 上看。不过需要确认每个intent 下的entity都考虑到了。

**Comment by mushr6om7** [comment]
v3.0里，除了replyPlace，其他的intent能想到的都列上了，还补充了相应的语料。

replyPlace我补充了几个，但是因为`北京，最好下午出发`这句有争议，而补充的语料与这句相似，所以等确定是否放在这个intent以后，我再把更新的intent发给你。
![image](https://user-images.githubusercontent.com/32808045/33175248-15aee8d0-d096-11e7-8ce8-2ac679661fad.png)
![image](https://user-images.githubusercontent.com/32808045/33175259-1bc744c4-d096-11e7-84d1-1a4626dca9f1.png)
