### ISSUE TITLE
有些地点识别不到，如拉斯维加斯。有些地点在第一次识别不了，后来又能识别了，如海南

### ISSUE THREAD

**Issue by thesillydog** [lijiarui/ticket-bot#87]
地点识别不到时，提示一下到底哪些能识别？？

![image](https://user-images.githubusercontent.com/9498159/33231123-f19afe52-d22a-11e7-8e1b-239b6d4625c4.png)

![image](https://user-images.githubusercontent.com/9498159/33231130-02c5abc8-d22b-11e7-8e89-e5a68ea5c866.png)

**Comment by lijiarui** [comment]
@thesillydog 需要完整的把整个对话复现出来。这样不能解决问题。
