### ISSUE TITLE
`帮我订一张去香港的机票` 实体抽取错误

### ISSUE THREAD

**Issue by lijiarui** [lijiarui/ticket-bot#93]
![image](https://user-images.githubusercontent.com/6419514/33240575-ed64eabe-d2f2-11e7-8e8b-4f523b9dfebc.png)

把香港识别成了departTimePeriod

**Comment by mushr6om7** [comment]
我这里是没有问题的
![image](https://user-images.githubusercontent.com/32808045/33241039-3ff2fd90-d2fb-11e7-8b2a-351032d4882a.png)

**Comment by lijiarui** [comment]
新版没问题了
